### ISSUE TITLE
Possible missmatch of selectors

### ISSUE THREAD

**Issue by IngwiePhoenix** [os-js/osjs-example-application#1]
Within `index.js` the ID used for the application window is: `MyApplicationWindow` and in the `index.scss` file, it is `.Window_MyApplication` - where it should probably be `MyApplicationWindow` instead? It just seemed off, so I put it here :)

**Comment by andersevenrud** [comment]
Nice catch. Moved to https://github.com/os-js/osjs-client/issues/66
